### ISSUE TITLE
Prevents Password Recovery link to be sent

### ISSUE THREAD

**Issue by mediaclinic** [unclecheese/silverstripe-permamail#9]
If in use, sends empty password recovery email.

**Comment by purplespider** [comment]
Looks like 9b2d640e923fc2ed9c40709d7dfda487e74bf037 didn't actually fix the forgotten password e-mails, it just made it so a blank e-mail was sent instead of no e-mail.

To work around this, I am adding the following config.yml (to disable the module's Injections):
````
---
Name: custompermamail
After: '*'
---
Injector:
  Email:
    class: Email
  Member_ForgotPasswordEmail:
    class: Member_ForgotPasswordEmail  
  Member_ChangePasswordEmail:
    class: Member_ChangePasswordEmail
  MemberConfirmationEmail:
    class: MemberConfirmationEmail
````

And then instead of `new Email()`, use `new Permamail()`
